### ISSUE TITLE
WOOTIC NOT SENDING DATA TO MAUTIC

### ISSUE THREAD

**Issue by dewalemichael** [maxitromer/wootic#3]
I am using current woocommerce version, current wordpress and current mautic plugin.

THE ISSUE
Upon activating wootic I tried setting up wootic to use the API, however no data get sent to mautic, after place order or successful payment.

I am using Paystack as a payment gateway for woocommerce.

Here is a sample order url: https://www.beautyandsalonmarketing.com/checkout/?add-to-cart=3501

I have also cleared mautic cache. I use cpanel.

I have attached my wootic setup in wordpress in case there is an error 
![woootic1](https://user-images.githubusercontent.com/51846239/73700867-021c7d80-46e8-11ea-8012-df9cb225a647.jpg)
![woootic2](https://user-images.githubusercontent.com/51846239/73700928-4576ec00-46e8-11ea-9914-6fe61714caea.jpg)

Kindly revert.

Regards

**Comment by maxitromer** [comment]
Hi @dewalemichael !

Your Mautic API is enabled?

If not please enable it,clear your cache again and test.

IMPORTANT: `Enable HTTP basic Auth` must be enabled too.

Here is how to do it:

![mautic-api-settings](https://user-images.githubusercontent.com/6311835/73707860-6be25a80-46db-11ea-8867-247e043ce035.png)

https://magefan.com/blog/how-to-enable-mautic-api

Let me know.

**Comment by dewalemichael** [comment]
Thank you for your feedback. Was helpful

After the activation of the API HTTP, I was able to receive data in mautic. Thank you for your help!

Quick question,
1. With Wootic API, I observed the data collected is slower to display in mautic? Is this correct pls?

2. What happens if a shopper buys the same woocommerce product say more than once, is Wootic able to identify the contact's frequency of order or how many times this Customer has purchased?

3.Please is there a way to create or put the contact from woocommerce-wootic in a segment?

3b. The only option I see to be able to trigger automation for woocommerce-wootic lead is to trigger an Automation targeting the tags?

Is this correct or could you suggest another better way?

4. I also observed a lead isn't created instantly he placed an order , the contact gets to be created only after successful order completion... But how can I track customers who abandon their cart? In order to trigger a cart reminder email?

Thank you

PS.
(I would want to make a suggestion)
Kindly help Wootic users with a more detailed guide on how to use the form option... 
What you currently have, doesn't include a detailed use case example... To ensure the set up is done right.

Thanks for making this plugin.

**Comment by tiagorodriguesdev** [comment]
Answering as a user for a month:

> With Wootic API, I observed the data collected is slower to display in mautic? Is this correct pls?

1 - It also depends on your servers. My configs sends the data and add the tags almost in real time.

> What happens if a shopper buys the same woocommerce product say more than once, is Wootic able to identify the contact's frequency of order or how many times this Customer has purchased?

2- Not yet, but it could be assigned as a Feature Request because it's possible to make it happen. A simple contact field could be added simultaneously with the tag that is a number and, for each purchase, increment if the tag "product_sku_tag_completed" already exists.

> 3.Please is there a way to create or put the contact from woocommerce-wootic in a segment?

Yes. Create a segment and use the filter "tag" to include all "product_sku_tag_completed" and "product_sku_tag_processing" to this segment.
This can work for a small/medium number of produtcs. For large ecomms you may add a general tag for all purchases that identify all buyers as buyers from your ecomm. (Feature Request)

> The only option I see to be able to trigger automation for woocommerce-wootic lead is to trigger an Automation targeting the tags?

Answered on "3".

> I also observed a lead isn't created instantly he placed an order , the contact gets to be created only after successful order completion... But how can I track customers who abandon their cart? In order to trigger a cart reminder email?

You can't track them yet. This feature would use a lot of machine power and I recommend you to use another tool that already exists to make it happen. (AutomateWoo, for instance. - Paid)

_PLEASE NOTE THAT PRODUCT_SKU_TAG IS JUST A PLACEHOLDER. YOU NEED TO USE YOUR OWN TAGS_

**Comment by dewalemichael** [comment]
Thank you for these clarifications, I am pleased.

I have implemented your suggestion in creating the segment, and its working.

regards

**Comment by maxitromer** [comment]
@TiagoRodrigues thanks for been here and your answers.

About your feature request:

![general_tags](https://user-images.githubusercontent.com/6311835/74087964-f32f2580-4a6f-11ea-98e1-50620110ae65.png)

**Comment by dewalemichael** [comment]
Thank you, 

But Which of my request does your response refers please?
